services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Digicademy\CobjXslt\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'

  Digicademy\CobjXslt\ContentObject\XsltContentObject:
    tags:
      - name: frontend.contentobject
        identifier: 'XSLT'
